# core/games/mapgame_data.py
"""Curated countries for the !mapgame guessing game.

Well-known countries (including recognizable island nations like Fiji), each with
a pixel coordinate on assets/worldmap.png (1000x500) and a difficulty tier.
Hand-picked to avoid obscure micro-states nobody could name.
"""

COUNTRIES = [
    {"name": 'United States', "emoji": '🇺🇸', "x": 227.8, "y": 141.7, "difficulty": 1},
    {"name": 'Canada', "emoji": '🇨🇦', "x": 205.6, "y": 94.4, "difficulty": 1},
    {"name": 'Brazil', "emoji": '🇧🇷', "x": 355.6, "y": 277.8, "difficulty": 1},
    {"name": 'United Kingdom', "emoji": '🇬🇧', "x": 494.4, "y": 100.0, "difficulty": 1},
    {"name": 'France', "emoji": '🇫🇷', "x": 505.6, "y": 122.2, "difficulty": 1},
    {"name": 'Germany', "emoji": '🇩🇪', "x": 527.8, "y": 108.3, "difficulty": 1},
    {"name": 'Italy', "emoji": '🇮🇹', "x": 533.3, "y": 133.3, "difficulty": 1},
    {"name": 'Spain', "emoji": '🇪🇸', "x": 488.9, "y": 138.9, "difficulty": 1},
    {"name": 'Russia', "emoji": '🇷🇺', "x": 777.8, "y": 77.8, "difficulty": 1},
    {"name": 'China', "emoji": '🇨🇳', "x": 788.9, "y": 152.8, "difficulty": 1},
    {"name": 'India', "emoji": '🇮🇳', "x": 719.4, "y": 188.9, "difficulty": 1},
    {"name": 'Japan', "emoji": '🇯🇵', "x": 883.3, "y": 147.2, "difficulty": 1},
    {"name": 'Australia', "emoji": '🇦🇺', "x": 872.2, "y": 319.4, "difficulty": 1},
    {"name": 'Mexico', "emoji": '🇲🇽', "x": 216.7, "y": 186.1, "difficulty": 1},
    {"name": 'Egypt', "emoji": '🇪🇬', "x": 583.3, "y": 175.0, "difficulty": 1},
    {"name": 'South Africa', "emoji": '🇿🇦', "x": 569.4, "y": 330.6, "difficulty": 1},
    {"name": 'Argentina', "emoji": '🇦🇷', "x": 322.2, "y": 355.6, "difficulty": 1},
    {"name": 'Sweden', "emoji": '🇸🇪', "x": 541.7, "y": 77.8, "difficulty": 2},
    {"name": 'Norway', "emoji": '🇳🇴', "x": 525.0, "y": 80.6, "difficulty": 2},
    {"name": 'Poland', "emoji": '🇵🇱', "x": 552.8, "y": 105.6, "difficulty": 2},
    {"name": 'Turkey', "emoji": '🇹🇷', "x": 597.2, "y": 141.7, "difficulty": 2},
    {"name": 'Saudi Arabia', "emoji": '🇸🇦', "x": 625.0, "y": 183.3, "difficulty": 2},
    {"name": 'Iran', "emoji": '🇮🇷', "x": 647.2, "y": 161.1, "difficulty": 2},
    {"name": 'Thailand', "emoji": '🇹🇭', "x": 780.6, "y": 208.3, "difficulty": 2},
    {"name": 'Vietnam', "emoji": '🇻🇳', "x": 794.4, "y": 205.6, "difficulty": 2},
    {"name": 'Indonesia', "emoji": '🇮🇩', "x": 833.3, "y": 255.6, "difficulty": 2},
    {"name": 'Nigeria', "emoji": '🇳🇬', "x": 522.2, "y": 225.0, "difficulty": 2},
    {"name": 'Kenya', "emoji": '🇰🇪', "x": 605.6, "y": 250.0, "difficulty": 2},
    {"name": 'Morocco', "emoji": '🇲🇦', "x": 480.6, "y": 161.1, "difficulty": 2},
    {"name": 'Peru', "emoji": '🇵🇪', "x": 291.7, "y": 277.8, "difficulty": 2},
    {"name": 'Chile', "emoji": '🇨🇱', "x": 302.8, "y": 333.3, "difficulty": 2},
    {"name": 'Colombia', "emoji": '🇨🇴', "x": 297.2, "y": 238.9, "difficulty": 2},
    {"name": 'Greece', "emoji": '🇬🇷', "x": 561.1, "y": 141.7, "difficulty": 2},
    {"name": 'Portugal', "emoji": '🇵🇹', "x": 477.8, "y": 138.9, "difficulty": 2},
    {"name": 'Ukraine', "emoji": '🇺🇦', "x": 588.9, "y": 113.9, "difficulty": 2},
    {"name": 'South Korea', "emoji": '🇰🇷', "x": 855.6, "y": 150.0, "difficulty": 2},
    {"name": 'Pakistan', "emoji": '🇵🇰', "x": 694.4, "y": 166.7, "difficulty": 2},
    {"name": 'Philippines', "emoji": '🇵🇭', "x": 838.9, "y": 216.7, "difficulty": 2},
    {"name": 'New Zealand', "emoji": '🇳🇿', "x": 977.8, "y": 366.7, "difficulty": 2},
    {"name": 'Ireland', "emoji": '🇮🇪', "x": 477.8, "y": 102.8, "difficulty": 2},
    {"name": 'Iceland', "emoji": '🇮🇸', "x": 447.2, "y": 69.4, "difficulty": 2},
    {"name": 'Fiji', "emoji": '🇫🇯', "x": 978, "y": 297.2, "difficulty": 3},
    {"name": 'Madagascar', "emoji": '🇲🇬', "x": 630.6, "y": 302.8, "difficulty": 3},
    {"name": 'Cuba', "emoji": '🇨🇺', "x": 283.3, "y": 188.9, "difficulty": 3},
    {"name": 'Iraq', "emoji": '🇮🇶', "x": 619.4, "y": 158.3, "difficulty": 3},
    {"name": 'Afghanistan', "emoji": '🇦🇫', "x": 683.3, "y": 155.6, "difficulty": 3},
    {"name": 'Kazakhstan', "emoji": '🇰🇿', "x": 686.1, "y": 116.7, "difficulty": 3},
    {"name": 'Mongolia', "emoji": '🇲🇳', "x": 786.1, "y": 122.2, "difficulty": 3},
    {"name": 'Ethiopia', "emoji": '🇪🇹', "x": 611.1, "y": 225.0, "difficulty": 3},
    {"name": 'Ghana', "emoji": '🇬🇭', "x": 497.2, "y": 227.8, "difficulty": 3},
    {"name": 'Cameroon', "emoji": '🇨🇲', "x": 533.3, "y": 233.3, "difficulty": 3},
    {"name": 'Algeria', "emoji": '🇩🇿', "x": 508.3, "y": 172.2, "difficulty": 3},
    {"name": 'Libya', "emoji": '🇱🇾', "x": 547.2, "y": 175.0, "difficulty": 3},
    {"name": 'Venezuela', "emoji": '🇻🇪', "x": 316.7, "y": 230.6, "difficulty": 3},
    {"name": 'Bolivia', "emoji": '🇧🇴', "x": 322.2, "y": 297.2, "difficulty": 3},
    {"name": 'Paraguay', "emoji": '🇵🇾', "x": 338.9, "y": 313.9, "difficulty": 3},
    {"name": 'Finland', "emoji": '🇫🇮', "x": 572.2, "y": 72.2, "difficulty": 3},
    {"name": 'Romania', "emoji": '🇷🇴', "x": 569.4, "y": 122.2, "difficulty": 3},
    {"name": 'Nepal', "emoji": '🇳🇵', "x": 733.3, "y": 172.2, "difficulty": 3},
    {"name": 'Sri Lanka', "emoji": '🇱🇰', "x": 725.0, "y": 230.6, "difficulty": 3},
    {"name": 'Malaysia', "emoji": '🇲🇾', "x": 811.1, "y": 238.9, "difficulty": 3},
    {"name": 'Papua New Guinea', "emoji": '🇵🇬', "x": 900.0, "y": 266.7, "difficulty": 3},
    {"name": 'Panama', "emoji": '🇵🇦', "x": 277.8, "y": 225.0, "difficulty": 3},
    {"name": 'Jamaica', "emoji": '🇯🇲', "x": 286.1, "y": 200.0, "difficulty": 3},
    {"name": 'Tunisia', "emoji": '🇹🇳', "x": 525.0, "y": 155.6, "difficulty": 3},
    {"name": 'Oman', "emoji": '🇴🇲', "x": 655.6, "y": 191.7, "difficulty": 3},
    {"name": 'Uzbekistan', "emoji": '🇺🇿', "x": 677.8, "y": 136.1, "difficulty": 3},
    {"name": 'Angola', "emoji": '🇦🇴', "x": 550.0, "y": 283.3, "difficulty": 3},
]

# accepted alternate spellings -> canonical name
ALIASES = {
    'usa': 'United States',
    'us': 'United States',
    'america': 'United States',
    'uk': 'United Kingdom',
    'britain': 'United Kingdom',
    'england': 'United Kingdom',
    'uae': 'United Arab Emirates',
    'south korea': 'South Korea',
    'korea': 'South Korea',
    'nz': 'New Zealand',
    'png': 'Papua New Guinea',
}